#!/bin/bash

########################################################################
# INSTALLATION
########################################################################

## Add the repo for RabbitMQ
sudo echo 'deb http://www.rabbitmq.com/debian/ testing main' >> /etc/apt/sources.list

## Add the Auth keys
sudo wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
sudo apt-key add rabbitmq-signing-key-public.asc

## Update and install
sudo apt-get update
sudo apt-get install -y rabbitmq-server

rabbitmqctl add_user admin adminpass
rabbitmqctl set_user_tags admin administrator
rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
rabbitmqctl delete_user guest

FILE="
# ##############################
# RABBITMQ SERVER CONFIGURATION
#
# All of the parameters below can also
#   be set as environment variables
#   using the prefix "RABBIT_"
#   i.e.  export RABBITMQ_NODE_PORT=5672
## ##############################
 
# ##########################
# Defaults to the empty string
#   meaning bind to all network interfaces
# Change to bind to one network interface only
# ##########################
# NODE_IP_ADDRESS=
# NODE_PORT=5672
 
# ##########################
# Unix, Linux: `env hostname`
# MacOSX: `env hostname -s`
# The name of the current machine
# ##########################
# HOSTNAME=
 
# ##########################
# The name of the current machine
# ##########################
# COMPUTERNAME=
 
# ##########################
# This base directory contains sub-directories for
#   server's db and log files
# Alternatively, set MNESIA_BASE and LOG_BASE individually
# ##########################
# BASE=
 
# ##########################
# Unix: rabbit@$HOSTNAME
# The node name should be unique per erlang-node-and-machine combination
# To run multiple nodes, see the clustering guide
# ##########################
# NODENAME=
 
# ##########################
# If the configuration file is present it is used by the server
# The .config extension is automatically appended
# This file is also used to auto-configure RabbitMQ clusters
# Example:
#   Config file location and new filename bunnies.config
#   CONFIG_FILE=/usr/local/etc/rabbitmq/bunnies
# ##########################
CONFIG_FILE=/etc/rabbitmq/rabbitmq
 
# ##########################
# Mac: /var/lib/rabbitmq/mnesia
# The Mnesia database files directory
#
# MNESIA_DIR will be assembled as MNESIA_BASE/NODENAME
# ##########################
# MNESIA_BASE=
# MNESIA_DIR=
 
# ##########################
# Log files generated by the server will be placed in this directory.
# ##########################
# LOG_BASE=/var/log/rabbitmq
 
# ##########################
# The plugins directory
# ##########################
PLUGINS_DIR=/etc/rabbitmq/plugins
 
# ##########################
# This file declares explicitly enabled plugins
# ##########################
ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins
"
sudo echo $FILE > /etc/rabbitmq/rabbitmq-env.conf

sudo service rabbitmq-server restart

echo '...............................................................'
echo 'Current set up:'
echo '...............................................................'
echo 'RabbitMQ user: admin'
echo 'RabbitMQ pass: adminpass'
echo ''
echo '...............................................................'
echo 'Change the password by running the following command:'
echo '' 
echo 'rabbitmqctl change_password admin <new_password>' 
echo '' 
